numbers = [57,59,65,20,25,50]
print("Simple list ",numbers)
numbers.append(60)
print("Appended the 60 usingh append()",numbers)
numbers.insert(0,25)
print("inserted 25 in 0 pos using insert()",numbers)
numbers.remove(20)
print("removed 20 from list",numbers)
numbers.pop()
print("You can remove last value using pop here us can see .pop()",numbers)
print("using index you wil get index of number for 65 ",numbers.index(65))
print("for counting the particular number in list use .count for 25 ",numbers.count(25))
print("For sorting the list use sort()")
numbers.sort()
print(numbers)
print("For copy use .copy() copied list 1 to list 2")
numbers2 = numbers.copy()
print("numbers from number list 1 : ",numbers)
print("numbers from number list 2 : ",numbers2)
numbers.clear()
print("Cleared the list using clear()",numbers)